[[docs]]
  name = "Software"
  weight = 10
  identifier = "software"
  url = "/docs/software/"

[[docs]]
  name = "Hardware"
  weight = 20
  identifier = "hardware"
  url = "/docs/hardware/"

  [[docs]]
    name = "3D Files"
    weight = 30
    identifier = "3d files"
    url = "/docs/3d_files/"

[[main]]
 name = "Docs"
 url = "/docs/"
 weight = 10

[[main]]
 name = "Blog"
 url = "/blog/"
 weight = 20

[[social]]
  name = "Hackaday"
  pre = "images/terminal.svg"
  url = "https://hackaday.io/project/168668-paperdink"

[[social]]
  name = "GitHub"
  pre = "images/github.svg"
  url = "https://github.com/rgujju/paperdink"

[[social]]
  name = "Instagram"
  pre = "images/instagram.svg"
  url = "https://www.instagram.com/paperd.ink/"

[[social]]
  name = "Twitter"
  pre = "images/twitter.svg"
  url = "https://twitter.com/paperddotink"

[[social]]
  name = "prasad@paperd.ink"
  pre = "images/mail.svg"
  url = "mailto:prasad@paperd.ink"

[[footer]]

